apiVersion: apps/v1
kind: Deployment
metadata:
  name: parser-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parser-app
  template:
    metadata:
      labels:
        app: parser-app
    spec:
      containers:
        - name: parser-app
          image: joshuajebaraj/parser-app:v1
          ports:
            - containerPort: 1337
          env:
            - name: DATABASE_URI
              value: mongodb://mongo:27017
            - name: MASTER_KEY	
              value: 123456789
            - name: APP_ID
              value: 123
          imagePullPolicy: Always
